# Generated by Django 5.2.6 on 2025-10-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0002_remove_reservation_date_remove_reservation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image_url',
            new_name='image',
        ),
    ]
