# Generated by Django 5.2.6 on 2025-10-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0004_remove_reservation_max_guest_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_guest_count',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
