# Generated by Django 5.2.6 on 2025-10-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0005_restaurant_max_guest_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_type',
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ManyToManyField(related_name='cuisines', to='rr_app.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
