# Generated by Django 5.2.6 on 2025-10-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0006_remove_restaurant_cuisine_type_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Restaurant closing time', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Restaurant opening time', null=True),
        ),
    ]
