# Generated by Django 5.2.6 on 2025-10-27 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0007_restaurant_closing_time_restaurant_opening_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
