# Generated by Django 5.2.6 on 2025-10-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0008_remove_reservation_table_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum price per person', max_digits=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum price per person', max_digits=8),
        ),
    ]
