# Generated by Django 5.2.6 on 2025-10-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0009_remove_restaurant_price_restaurant_price_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum food price', max_digits=8),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum food price', max_digits=8),
        ),
    ]
